export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';


export const MEMBER_REGISTER_LOADING='MEMBER_REGISTER_LOADING';
export const MEMBER_REGISTER_SUCCESS='MEMBER_REGISTER_SUCCESS';
export const MEMBER_REGISTER_FAIL='MEMBER_REGISTER_FAIL';

export const VIEW_MEMBER_PROFILE_LOADING="VIEW_MEMBER_PROFILE_LOADING";
export const VIEW_MEMBER_PROFILE_SUCCESS="VIEW_MEMBER_PROFILE_SUCCESS";
export const VIEW_MEMBER_PROFILE_FAIL="VIEW_MEMBER_PROFILE_FAIL"

export const VIEW_ADMIN_PROFILE_LOADING="VIEW_ADMIN_PROFILE_LOADING";
export const VIEW_ADMIN_PROFILE_SUCCESS="VIEW_ADMIN_PROFILE_SUCCESS";
export const VIEW_ADMIN_PROFILE_FAIL="VIEW_ADMIN_PROFILE_FAIL"

export const FETCH_ALL_COURSES_LOADING="FETCH_ALL_COURSES_LOADING"
export const FETCH_ALL_COURSES_SUCCESS="FETCH_ALL_COURSES_SUCCESS"
export const FETCH_ALL_COURSES_FAIL="FETCH_ALL_COURSES_FAIL"

export const GET_ONE_COURSE_LOADING="GET_ONE_COURSE_LOADING"
export const GET_ONE_COURSE_SUCCESS="GET_ONE_COURSE_SUCCESS"
export const GET_ONE_COURSE_FAIL="GET_ONE_COURSE_FAIL"


export const FETCH_ALL_CATEGORIES_LOADING="FETCH_ALL_CATEGORIES_LOADING"
export const FETCH_ALL_CATEGORIES_SUCCESS="FETCH_ALL_CATEGORIES_SUCCESS"
export const FETCH_ALL_CATEGORIES_FAIL="FETCH_ALL_CATEGORIES_FAIL"

export const FETCH_ALL_LECTURES_LOADING="FETCH_ALL_LECTURES_LOADING"
export const FETCH_ALL_LECTURES_SUCCESS="FETCH_ALL_LECTURES_SUCCESS"
export const FETCH_ALL_LECTURES_FAIL="FETCH_ALL_LECTURES_FAIL"

export const REGISTER_LECTURE_LOADING = 'REGISTER_LECTURE_LOADING';
export const REGISTER_LECTURE_SUCCESS = 'REGISTER_LECTURE_SUCCESS';
export const REGISTER_LECTURE_FAIL = 'REGISTER_LECTURE_FAIL';

export const ADD_NEW_COURSE_LOADING='ADD_NEW_COURSE_LOADING'
export const ADD_NEW_COURSE_SUCCESS='ADD_NEW_COURSE_SUCCESS'
export const ADD_NEW_COURSE_FAIL='ADD_NEW_COURSE_FAIL'

export const FETCH_COURSE_LESSONS_LOADING = "FETCH_COURSE_LESSONS_LOADING"
export const FETCH_COURSE_LESSONS_SUCCESS = "FETCH_COURSE_LESSONS_SUCCESS"
export const FETCH_COURSE_LESSONS_FAIL = "FETCH_COURSE_LESSONS_FAIL"