export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';

export const MEMBER_LOGIN_LOADING = 'MEMBER_LOGIN_LOADING';
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS';
export const MEMBER_LOGIN_FAIL = 'MEMBER_LOGIN_FAIL';

export const MEMBER_REGISTER_LOADING='MEMBER_REGISTER_LOADING';
export const MEMBER_REGISTER_SUCCESS='MEMBER_REGISTER_SUCCESS';
export const MEMBER_REGISTER_FAIL='MEMBER_REGISTER_FAIL';

export const VIEW_MEMBER_PROFILE_LOADING="VIEW_MEMBER_PROFILE_LOADING";
export const VIEW_MEMBER_PROFILE_SUCCESS="VIEW_MEMBER_PROFILE_SUCCESS";
export const VIEW_MEMBER_PROFILE_FAIL="VIEW_MEMBER_PROFILE_FAIL"