export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';

export const MEMBER_LOGIN_LOADING = 'MEMBER_LOGIN_LOADING';
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS';
export const MEMBER_LOGIN_FAIL = 'MEMBER_LOGIN_FAIL';

export const MEMBER_REGISTER_LOADING='MEMBER_REGISTER_LOADING';
export const MEMBER_REGISTER_SUCCESS='MEMBER_REGISTER_SUCCESS';
export const MEMBER_REGISTER_FAIL='MEMBER_REGISTER_FAIL';

export const VIEW_MEMBER_PROFILE_LOADING="VIEW_MEMBER_PROFILE_LOADING";
export const VIEW_MEMBER_PROFILE_SUCCESS="VIEW_MEMBER_PROFILE_SUCCESS";
export const VIEW_MEMBER_PROFILE_FAIL="VIEW_MEMBER_PROFILE_FAIL"

export const ADMIN_LOGIN_LOADING = 'ADMIN_LOGIN_LOADING';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const VIEW_ADMIN_PROFILE_LOADING="VIEW_ADMIN_PROFILE_LOADING";
export const VIEW_ADMIN_PROFILE_SUCCESS="VIEW_ADMIN_PROFILE_SUCCESS";
export const VIEW_ADMIN_PROFILE_FAIL="VIEW_ADMIN_PROFILE_FAIL"

export const FETCH_ALL_COURSES_LOADING="FETCH_ALL_COURSES_LOADING"
export const FETCH_ALL_COURSES_SUCCESS="FETCH_ALL_COURSES_SUCCESS"
export const FETCH_ALL_COURSES_FAIL="FETCH_ALL_COURSES_FAIL"

export const FETCH_ALL_CATEGORIES_LOADING="FETCH_ALL_CATEGORIES_LOADING"
export const FETCH_ALL_CATEGORIES_SUCCESS="FETCH_ALL_CATEGORIES_SUCCESS"
export const FETCH_ALL_CATEGORIES_FAIL="FETCH_ALL_CATEGORIES_FAIL"

export const FETCH_ALL_LECTURES_LOADING="FETCH_ALL_LECTURES_LOADING"
export const FETCH_ALL_LECTURES_SUCCESS="FETCH_ALL_LECTURES_SUCCESS"
export const FETCH_ALL_LECTURES_FAIL="FETCH_ALL_LECTURES_FAIL"